import { experience } from './profile-data';

const linkedin = 'https://www.linkedin.com/in/ddonofrio03/';
export default function Home() {
  return <main id="top">
    <a className="skip" href="#about">Skip to content</a>
    <header className="nav"><nav aria-label="Main navigation"><a href="#about">About</a><a href="#experience">Experience</a><a href="#contact">Connect <span>↗</span></a></nav></header>
    <section className="hero" aria-labelledby="hero-title">
      <div className="hero-meta"><span>COMMUNITY. COMMUNICATION. PUBLIC AFFAIRS.</span></div>
      <div className="hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="dot"/> COMMUNITY ENGAGEMENT · PUBLIC RELATIONS · GOVERNMENT AFFAIRS</p><h1 id="hero-title">David<br/><em>D’Onofrio</em></h1><p className="intro">Strategic communications and public affairs leadership. More than 30 years connecting communities, companies and decision-makers to advance complex projects.</p><a className="round-link" href="#about"><span className="circle">↓</span> Professional background</a></div><figure className="portrait"><div className="portrait-frame"><img src="/david.jpg" width="1258" height="1022" alt="Dave D’Onofrio smiling" fetchPriority="high"/><span className="portrait-seal" aria-hidden="true">PEOPLE<br/>FIRST</span></div><figcaption><span>SVP, RenUSA · Founder, The Casey Group</span></figcaption></figure></div>
      <div className="hero-bottom"><span>LEESBURG, VIRGINIA · NATIONAL EXPERIENCE</span><span>SCROLL TO EXPLORE ↓</span></div>
    </section>
    <section id="about" className="about section"><p className="eyebrow">PROFESSIONAL PROFILE</p><h2>Complex projects.<br/>Clear <em>direction.</em></h2><div className="about-text"><p>He brings more than 30 years of experience in strategic communications, government affairs and community engagement.</p><p>His work spans complex regulatory matters, major development proposals, professional sports and renewable energy. He develops communications strategies that engage stakeholders, build relationships with decision-makers and support project approvals.</p><p>Through close client partnerships, he aligns traditional media, social campaigns and direct outreach to communities and elected officials with each project’s goals.</p><a className="text-link" href={linkedin} target="_blank" rel="noreferrer">View LinkedIn profile <span>↗</span></a></div></section>
    <section className="impact section" aria-label="Career highlights"><article><strong>30+</strong><p>Years in communications,<br/>government & community relations</p></article><article><strong>$1.5B+</strong><p>In mixed-use projects supported<br/>by media and community plans</p></article><article><strong>$225M</strong><p>Budget responsibility on a<br/>San Francisco Bay development</p></article></section>
    <section id="experience" className="experience section"><div className="career-heading"><p className="eyebrow">EXPERIENCE THAT MOVES THINGS FORWARD</p><h2>Professional<br/><em>experience.</em></h2><p>From Washington advocacy to major developments, professional sports and renewable energy.</p></div><div className="timeline">{experience.map((job)=><article className="job" key={job.company+job.role}><div className="job-date">{job.dates}</div><div><h3>{job.company}</h3><p className="role">{job.role}</p>{job.location && <p className="location">{job.location}</p>}{job.description && <p>{job.description}</p>}{job.highlights && <ul>{job.highlights.map(item=><li key={item}>{item}</li>)}</ul>}</div></article>)}</div></section>
    <section id="perspective" className="perspective section"><p className="eyebrow">HOW I WORK</p><h2>Strategy grounded<br/>in <em>experience.</em></h2><div className="principles"><article><h3>Clarity.</h3><p>Strategic messaging, media relations and crisis communications that make complex issues understandable.</p></article><article><h3>Connection.</h3><p>Community engagement and grassroots outreach that build relationships with the people a project affects.</p></article><article><h3>Perspective.</h3><p>Government affairs and political strategy grounded in decades of work with decision-makers.</p></article></div><div className="skills"><h3>Professional skills</h3><ul><li>Media Relations</li><li>Public Relations</li><li>Strategic Communications</li><li>Corporate Communications</li><li>Press Releases</li><li>Lobbying</li><li>Grassroots Lobbying</li><li>Grassroots Communication</li><li>Local Government Relations</li><li>Strategy</li></ul></div></section>
    <section className="education section"><p className="eyebrow">FOUNDATIONS</p><h2>Education &<br/><em>foundations.</em></h2><div className="education-grid"><article><span>1989 — 1993</span><h3>Wesleyan University</h3><p>Bachelor of Science, Government</p><p>Senior paper: Departmentalism vs. Judicial Supremacy.<br/>Football, golf team and Delta Kappa Epsilon.<br/>Coursework: Constitutional Law.</p></article><article><span>1985 — 1989</span><h3>James Caldwell High School</h3><p>High school / secondary diploma studies.</p><p>Language: English, native or bilingual proficiency.</p></article></div></section>
    <section className="community section"><p className="eyebrow">COMMUNITY LEADERSHIP</p><h2>Public service.<br/><em>Local commitment.</em></h2><div className="community-grid"><article><span>Aug 2004 — Jun 2021</span><h3>Leesburg Football Club</h3><p className="role">Coach & Board Member</p><p>Coached at challenge and travel levels.</p></article><article><span>Jun 2011 — Sep 2018</span><h3>Loudoun Hunger Relief</h3><p className="role">Board Member · Poverty Alleviation</p><p>Served on the board of a nonprofit whose work included distributing 1.2 million pounds of food supplies to 22,000 households.</p></article><article><span>Jun 2009 — Nov 2018</span><h3>Spring Lakes Home Owners Association</h3><p className="role">President & Vice President</p><p>Nearly a decade of neighborhood service, including seven years as president.</p></article><article><span>Feb 2015 — Jan 2018</span><h3>Republican Party of Virginia</h3><p className="role">Director of Communication</p><p>Directed media relations, messaging, social and strategic communications for the state party.</p></article></div><div className="affiliations"><h3>Professional organizations</h3><p>Loudoun County Chamber of Commerce <span>January 2007 — Present</span></p><p>Loudoun County CEO Cabinet <span>April 2015 — December 2024</span></p><p className="affiliation-note">Both affiliations associated with The Casey Group.</p></div></section>
    <section className="recommendations section"><p className="eyebrow">PROFESSIONAL RECOMMENDATIONS</p><h2>Trusted by<br/><em>clients & colleagues.</em></h2><div className="quotes"><figure><blockquote>“He delivers on what he promises.”</blockquote><figcaption>Bob Steere<span>Client</span></figcaption></figure><figure><blockquote>“David is the consummate professional”</blockquote><figcaption>Glen Caroline<span>Direct manager</span></figcaption></figure><figure><blockquote>“David has my highest recommendation.”</blockquote><figcaption>Mark Faris<span>Client</span></figcaption></figure></div><a className="text-link" href="https://www.linkedin.com/in/ddonofrio03/details/recommendations/" target="_blank" rel="noreferrer">Read the full recommendations <span>↗</span></a></section>
    <section className="family section"><p className="eyebrow">PART OF SOMETHING BIGGER</p><div><h2>A family<br/>of <em>builders.</em></h2><p>At DONOFR.IO, we bring together experience across AI, sales, marketing, and public affairs.</p><a className="text-link" href="https://donofr.io/" target="_blank" rel="noreferrer">Meet the family <span>↗</span></a></div></section>
    <footer id="contact" className="section contact"><p className="eyebrow">DISCUSS YOUR NEXT PROJECT.</p><a className="contact-title" href="mailto:dave@donofr.io">Connect.<span>↗</span></a><div className="contact-links"><a href="mailto:dave@donofr.io">dave@donofr.io</a><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Dave D’Onofrio</span><a href="#top">BACK TO TOP ↑</a><span>DAVE.DONOFR.IO</span></div></footer>
  </main>;
}
